-- 023_idempotency_and_status_fix.sql
-- Two changes:
--
-- A. Add client_request_id to cases for offline idempotency.
-- B. Fix case status transition graph:
--    - Remove: on_progress → closed (non-standard direct close)
--    - Keep standard flow only
--    - Add force_close_case() RPC for emergency admin close

-- ═══════════════════════════════════════════════════════════════════════════
-- A. IDEMPOTENCY: client_request_id column on cases
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Generated by the client when a draft is first created in IndexedDB.
-- Survives reconnect retries / sync queue re-executions.
-- UNIQUE(reporter_id, client_request_id) prevents duplicate case creation.
--
-- If create_case() is called with the same client_request_id by the same
-- authenticated user, it returns the already-created case_id without:
--   - generating a new case number
--   - inserting duplicate activity log
--   - sending duplicate notifications
--
-- The column is optional (NULL) for cases created via the web UI
-- without offline draft mode.

ALTER TABLE public.cases
  ADD COLUMN IF NOT EXISTS client_request_id uuid;

-- Unique constraint: same reporter + same client_request_id = same case
CREATE UNIQUE INDEX IF NOT EXISTS cases_idempotency_uq
  ON public.cases (reporter_id, client_request_id)
  WHERE client_request_id IS NOT NULL;

-- ═══════════════════════════════════════════════════════════════════════════
-- B. STATUS TRANSITION: fix the trigger in 018
--    Replace the existing trg_case_status_transition function
--    to remove on_progress → closed from the standard graph.
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Standard resolution flow:
--   open → on_progress → [waiting_repair →] waiting_verification → closed
--
-- Verification rejection:
--   waiting_verification → on_progress
--
-- Reopening:
--   closed → reopened → on_progress | waiting_repair | waiting_verification
--
-- Emergency close (admin only) via force_close_case() RPC:
--   any non-closed status → closed  (bypasses trigger via SECURITY DEFINER)
--
-- The trigger below enforces the STANDARD flow for all non-RPC direct writes.
-- force_close_case() sets a session variable to temporarily bypass.

CREATE OR REPLACE FUNCTION public.trg_case_status_transition()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_allowed_next text[];
  v_force_close  text;
BEGIN
  -- Skip if status hasn't changed
  IF NEW.status = OLD.status THEN
    RETURN NEW;
  END IF;

  -- Allow force_close bypass: set by force_close_case() RPC only
  v_force_close := current_setting('wact.force_close', true);
  IF v_force_close = 'true' THEN
    -- Force close is only allowed to → 'closed'
    IF NEW.status = 'closed' THEN
      IF NEW.status = 'closed' AND OLD.status <> 'closed' THEN
        NEW.closed_at = now();
      END IF;
      RETURN NEW;
    ELSE
      RAISE EXCEPTION 'force_close bypass only permitted for → closed transition';
    END IF;
  END IF;

  -- Standard transition graph (no direct on_progress → closed)
  v_allowed_next := CASE OLD.status
    WHEN 'open'                 THEN ARRAY['on_progress']
    WHEN 'on_progress'          THEN ARRAY['waiting_repair', 'waiting_verification']
    WHEN 'waiting_repair'       THEN ARRAY['on_progress', 'waiting_verification']
    WHEN 'waiting_verification' THEN ARRAY['closed', 'on_progress']
    WHEN 'closed'               THEN ARRAY['reopened']
    WHEN 'reopened'             THEN ARRAY['on_progress', 'waiting_repair', 'waiting_verification']
    ELSE ARRAY[]::text[]
  END;

  IF NOT (NEW.status = ANY(v_allowed_next)) THEN
    RAISE EXCEPTION
      'Invalid case status transition: % → % (case %). Standard flow: open→on_progress→waiting_verification→closed',
      OLD.status, NEW.status, NEW.id;
  END IF;

  -- Set closed_at when closing via verification
  IF NEW.status = 'closed' AND OLD.status <> 'closed' THEN
    NEW.closed_at = now();
  END IF;

  -- Clear closed_at when reopening
  IF NEW.status = 'reopened' AND OLD.status = 'closed' THEN
    NEW.closed_at = NULL;
  END IF;

  RETURN NEW;
END;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- C. force_close_case() RPC — emergency admin close
-- ═══════════════════════════════════════════════════════════════════════════
-- Requires: case.force_close capability (admin-only)
-- Mandatory: reason (NOT NULL)
-- Multi-step: set bypass → update status → clear bypass → log → notify

CREATE OR REPLACE FUNCTION public.force_close_case(
  p_case_id uuid,
  p_reason  text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor_id  uuid := auth.uid();
  v_case      record;
  v_assignee  uuid;
BEGIN
  IF v_actor_id IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_reason IS NULL OR trim(p_reason) = '' THEN
    RAISE EXCEPTION 'Reason is mandatory for force_close_case()';
  END IF;

  SELECT id, warehouse_id, status, reporter_id INTO v_case FROM public.cases WHERE id = p_case_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Case % not found', p_case_id; END IF;

  -- Requires dedicated force_close capability (admin only)
  IF NOT public.has_capability(v_case.warehouse_id, 'case.force_close') THEN
    RAISE EXCEPTION 'Permission denied: missing case.force_close capability';
  END IF;

  IF v_case.status = 'closed' THEN
    RAISE EXCEPTION 'Case is already closed';
  END IF;

  -- Set bypass session variable so trigger allows the transition
  PERFORM set_config('wact.force_close', 'true', true);  -- local = true (txn-scoped)

  -- Force close
  UPDATE public.cases
     SET status = 'closed', closed_at = now()
   WHERE id = p_case_id;

  -- Clear bypass (already txn-scoped, but explicit for clarity)
  PERFORM set_config('wact.force_close', 'false', true);

  -- Audit log
  PERFORM public.log_case_activity(p_case_id, 'force_closed',
    v_case.status, 'closed',
    jsonb_build_object(
      'reason',   p_reason,
      'actor_id', v_actor_id,
      'previous_status', v_case.status
    ));

  -- Notify reporter
  PERFORM public.send_notification(v_case.reporter_id, 'force_closed',
    'Case ditutup paksa oleh admin',
    p_reason,
    jsonb_build_object('case_id', p_case_id));

  -- Notify assignee if exists
  SELECT assignee_id INTO v_assignee
    FROM public.case_assignments
   WHERE case_id = p_case_id AND is_current = true;
  IF v_assignee IS NOT NULL AND v_assignee <> v_case.reporter_id THEN
    PERFORM public.send_notification(v_assignee, 'force_closed',
      'Case ditutup paksa oleh admin', p_reason,
      jsonb_build_object('case_id', p_case_id));
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.force_close_case(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.force_close_case(uuid, text) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- D. UPDATE create_case() to be idempotent via client_request_id
-- ═══════════════════════════════════════════════════════════════════════════
-- Replaces the create_case from migration 021.
-- Same signature + new parameter: p_client_request_id uuid DEFAULT NULL

CREATE OR REPLACE FUNCTION public.create_case(
  p_warehouse_id           uuid,
  p_title                  text,
  p_description            text DEFAULT NULL,
  p_category_id            uuid DEFAULT NULL,
  p_subcategory_id         uuid DEFAULT NULL,
  p_area_id                uuid DEFAULT NULL,
  p_location_id            uuid DEFAULT NULL,
  p_asset_id               uuid DEFAULT NULL,
  p_inspection_id          uuid DEFAULT NULL,
  p_priority               text DEFAULT 'medium',
  p_has_operational_impact boolean DEFAULT false,
  p_requires_maintenance   boolean DEFAULT false,
  p_source                 text DEFAULT 'direct',
  p_due_date               timestamptz DEFAULT NULL,
  -- Offline idempotency: generated by client when draft is first created.
  -- Same reporter + same client_request_id → returns existing case, no duplicate.
  p_client_request_id      uuid DEFAULT NULL
)
RETURNS uuid   -- returns case id (new or existing)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor_id     uuid := auth.uid();
  v_case_id      uuid;
  v_case_number  text;
  v_wh_code      text;
  v_wh_tz        text;
  v_seq          int;
  v_display_date text;
  v_local_date   date;
BEGIN
  -- 1. Validate actor
  IF v_actor_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- 2. IDEMPOTENCY CHECK — if client_request_id already used by this reporter,
  --    return the existing case_id immediately without any side-effects.
  IF p_client_request_id IS NOT NULL THEN
    SELECT id INTO v_case_id
      FROM public.cases
     WHERE reporter_id = v_actor_id
       AND client_request_id = p_client_request_id;

    IF FOUND THEN
      -- Already created — idempotent return, no new sequence/activity/notification
      RETURN v_case_id;
    END IF;
  END IF;

  -- 3. Validate capability
  IF NOT public.has_capability(p_warehouse_id, 'case.create') THEN
    RAISE EXCEPTION 'Permission denied: missing case.create capability in warehouse %', p_warehouse_id;
  END IF;

  -- 4. Validate warehouse is active
  SELECT code, timezone INTO v_wh_code, v_wh_tz
    FROM public.warehouses
   WHERE id = p_warehouse_id AND is_active = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Warehouse % not found or inactive', p_warehouse_id;
  END IF;

  -- 5. Validate priority
  IF p_priority NOT IN ('low', 'medium', 'high', 'critical') THEN
    RAISE EXCEPTION 'Invalid priority: %', p_priority;
  END IF;

  -- 6. Validate source
  IF p_source NOT IN ('direct', 'inspection') THEN
    RAISE EXCEPTION 'Invalid source: %', p_source;
  END IF;

  -- 7. Validate subcategory → category
  IF p_subcategory_id IS NOT NULL AND p_category_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.case_subcategories
       WHERE id = p_subcategory_id AND category_id = p_category_id
    ) THEN
      RAISE EXCEPTION 'Subcategory % does not belong to category %', p_subcategory_id, p_category_id;
    END IF;
  END IF;

  -- 8. Validate area / location / asset / inspection belong to same warehouse
  IF p_area_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM public.areas WHERE id = p_area_id AND warehouse_id = p_warehouse_id) THEN
      RAISE EXCEPTION 'Area % does not belong to warehouse %', p_area_id, p_warehouse_id;
    END IF;
  END IF;
  IF p_location_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM public.locations WHERE id = p_location_id AND warehouse_id = p_warehouse_id) THEN
      RAISE EXCEPTION 'Location % does not belong to warehouse %', p_location_id, p_warehouse_id;
    END IF;
  END IF;
  IF p_asset_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM public.assets WHERE id = p_asset_id AND warehouse_id = p_warehouse_id) THEN
      RAISE EXCEPTION 'Asset % does not belong to warehouse %', p_asset_id, p_warehouse_id;
    END IF;
  END IF;
  IF p_inspection_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM public.inspections WHERE id = p_inspection_id AND warehouse_id = p_warehouse_id) THEN
      RAISE EXCEPTION 'Inspection % does not belong to warehouse %', p_inspection_id, p_warehouse_id;
    END IF;
  END IF;

  -- 9. Generate case number atomically (warehouse-timezone-aware)
  v_local_date   := (now() AT TIME ZONE v_wh_tz)::date;
  v_display_date := to_char(now() AT TIME ZONE v_wh_tz, 'YYMMDD');

  INSERT INTO public.case_sequences (warehouse_id, sequence_date, last_sequence)
  VALUES (p_warehouse_id, v_local_date, 1)
  ON CONFLICT (warehouse_id, sequence_date)
  DO UPDATE SET last_sequence = public.case_sequences.last_sequence + 1
  RETURNING last_sequence INTO v_seq;

  v_case_number := 'WHC-' || v_wh_code || '-' || v_display_date || '-' || lpad(v_seq::text, 3, '0');

  -- 10. Insert case (with optional client_request_id for idempotency)
  INSERT INTO public.cases (
    case_number, title, description, category_id, subcategory_id,
    warehouse_id, area_id, location_id, asset_id, inspection_id,
    reporter_id, priority, status, has_operational_impact, requires_maintenance,
    source, due_date, client_request_id
  ) VALUES (
    v_case_number, p_title, p_description, p_category_id, p_subcategory_id,
    p_warehouse_id, p_area_id, p_location_id, p_asset_id, p_inspection_id,
    v_actor_id, p_priority, 'open', p_has_operational_impact, p_requires_maintenance,
    p_source, p_due_date, p_client_request_id
  )
  RETURNING id INTO v_case_id;

  -- 11. Log creation activity
  PERFORM public.log_case_activity(v_case_id, 'created', NULL, 'open', NULL);

  RETURN v_case_id;
END;
$$;

-- Update grants for new signature (old signature remains for backward compat via overloading)
REVOKE ALL ON FUNCTION public.create_case(uuid,text,text,uuid,uuid,uuid,uuid,uuid,uuid,text,boolean,boolean,text,timestamptz,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_case(uuid,text,text,uuid,uuid,uuid,uuid,uuid,uuid,text,boolean,boolean,text,timestamptz,uuid) TO authenticated;
